import { jsPDF } from 'jspdf'

export const exportHealthReport = (userData, assessments) => {
  const doc = new jsPDF()
  
  // Design system colors
  const primaryColor = '#10B981'
  const darkColor = '#0F172A'

  // Header
  doc.setFillColor(darkColor)
  doc.rect(0, 0, 210, 40, 'F')
  
  doc.setTextColor('#FFFFFF')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.text('PreventAI Health Report', 20, 25)
  
  doc.setFontSize(10)
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 150, 25)

  // User Info
  doc.setTextColor(darkColor)
  doc.setFontSize(14)
  doc.text('Patient Information', 20, 55)
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Email: ${userData?.email}`, 20, 65)
  doc.text(`Status: Verified AI Profile`, 20, 70)

  // Latest Assessments
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Latest Clinical Assessments', 20, 85)
  
  let yPos = 95
  assessments.slice(-5).reverse().forEach((a, i) => {
    // Background card for each assessment
    doc.setFillColor('#F8FAFC')
    doc.roundedRect(15, yPos - 5, 180, 25, 3, 3, 'F')
    
    doc.setTextColor(darkColor)
    doc.setFont('helvetica', 'bold')
    doc.text(`${a.type.toUpperCase()} Risk Assessment`, 20, yPos + 5)
    
    doc.setFont('helvetica', 'normal')
    doc.text(`Result: ${a.risk_category}`, 20, yPos + 12)
    
    doc.setTextColor(primaryColor)
    doc.setFont('helvetica', 'bold')
    doc.text(`${a.result?.probability}% Probability`, 150, yPos + 8)
    
    yPos += 30
  })

  // Footer
  doc.setTextColor('#94A3B8')
  doc.setFontSize(8)
  doc.text('Disclaimer: This report is generated by an AI model and should be reviewed by a medical professional.', 20, 280)

  doc.save(`PreventAI_Report_${new Date().getTime()}.pdf`)
}
